// d=領域ID, f=表, b=裏
window.CARDS = [
{d:1,f:"BigQuery ML の TRANSFORM 句",b:"前処理を学習時と推論時の両方に自動適用する。Training-Serving Skew の防止に有効。"},
{d:1,f:"Document AI",b:"請求書・領収書・身分証などの構造化データ抽出に特化した事前学習済み/カスタムプロセッサ。"},
{d:1,f:"AutoML を選ぶ状況",b:"独自のラベル付きデータがあり、コード最小で高精度なモデルが欲しいとき。"},
{d:1,f:"TPU / GPU / CPU の使い分け",b:"TPU：大規模行列演算・大バッチ。GPU：柔軟なDNN学習/推論。CPU：表形式・小規模・前処理。"},
{d:1,f:"Edge TPU / TFLite",b:"オンデバイス推論。低遅延・オフライン・プライバシー要件で使う。"},
{d:1,f:"Model Garden",b:"Google/OSS/パートナーのモデルを探索・デプロイ・チューニングできるカタログ。"},
{d:1,f:"Agent Builder",b:"ローコードでRAG・検索・エージェントを構築するサービス群。"},
{d:1,f:"ARIMA_PLUS",b:"BigQuery ML の時系列予測モデル。季節性・休日・外れ値を扱う。"},
{d:2,f:"Training-Serving Skew",b:"学習時と推論時で特徴量の計算や分布が異なる問題。前処理の共通化やFeature Storeで防ぐ。"},
{d:2,f:"データリーク",b:"予測時点で得られない情報（未来情報・目的変数由来）が学習に混入すること。時系列は時間で分割する。"},
{d:2,f:"Dataflow / Dataproc",b:"Dataflow：Beamでバッチ+ストリーム、サーバーレス。Dataproc：既存Spark/Hadoop資産の移行。"},
{d:2,f:"Vertex AI Feature Store",b:"特徴量の一元管理・再利用・オンライン/オフライン提供。"},
{d:2,f:"Explainable AI の手法",b:"Sampled Shapley、Integrated Gradients、XRAI。特徴量/画素ごとの寄与を示す。"},
{d:2,f:"Sensitive Data Protection",b:"旧 Cloud DLP。機微情報の検出とマスキング/トークン化。"},
{d:2,f:"クラス不均衡への対処",b:"クラス重み、オーバー/アンダーサンプリング、PR-AUC・F1での評価。"},
{d:2,f:"Vertex AI Experiments",b:"実験のパラメータ・メトリクス・成果物を記録し比較する。"},
{d:3,f:"Recall と Precision",b:"Recall：見逃しを減らす（陽性のうち拾えた割合）。Precision：誤検知を減らす（予測陽性のうち正解の割合）。"},
{d:3,f:"L1 と L2 正則化",b:"L1：スパース化・特徴量選択。L2：重みを小さく保ち過学習抑制。"},
{d:3,f:"MirroredStrategy / MultiWorkerMirroredStrategy / TPUStrategy",b:"単一マシン複数GPU / 複数マシン / TPU向けの tf.distribute 戦略。"},
{d:3,f:"データ並列とモデル並列",b:"データ並列：モデルを複製しデータを分割。モデル並列：モデルが1デバイスに載らないとき分割。"},
{d:3,f:"Vertex AI Vizier",b:"ベイズ最適化によるハイパーパラメータチューニング。少ない試行で収束。"},
{d:3,f:"RAG と ファインチューニングの使い分け",b:"RAG：最新/社内知識の反映・幻覚抑制。ファインチューニング：形式・トーン・タスク特化の安定化。"},
{d:3,f:"LoRA / PEFT",b:"モデルの一部のパラメータだけを学習する効率的なファインチューニング。コストを抑える。"},
{d:3,f:"RAGの構成",b:"文書 → チャンク分割 → Embedding → Vector Search → 関連チャンクをプロンプトに付与。"},
{d:3,f:"蒸留(Distillation)",b:"大モデルの出力を小モデルに学習させ、品質を保ちつつ低コスト・低遅延にする。"},
{d:4,f:"オンライン推論 vs バッチ推論",b:"オンライン：低遅延・リクエスト単位。バッチ：大量データを非同期で一括、低コスト。"},
{d:4,f:"traffic split",b:"同一Endpoint内でモデルごとにトラフィック割合を設定し、カナリア/A-Bテストを行う。"},
{d:4,f:"オートスケーリング",b:"min/max replica と使用率ターゲットで負荷に追従。コストと遅延のバランスを取る。"},
{d:4,f:"Private Endpoint / Private Service Connect",b:"インターネットに公開せずVPC内からのみ推論APIを利用する構成。"},
{d:4,f:"カスタムコンテナ",b:"事前構築コンテナ非対応のフレームワークや独自前処理に対応。predict/health の HTTP サーバを実装。"},
{d:4,f:"量子化(Quantization)",b:"重みを低精度（INT8等）にして推論を高速化・軽量化する。"},
{d:4,f:"Provisioned Throughput",b:"生成AIの容量を予約し、安定したスループット・遅延を確保する。"},
{d:5,f:"Vertex AI Pipelines",b:"KFP/TFXでML専用ワークフローをサーバーレス実行。メタデータ/リネージを自動追跡。"},
{d:5,f:"Cloud Composer",b:"マネージドAirflow。ML以外を含む広範なワークフロー・既存Airflow資産に。"},
{d:5,f:"MLOps 成熟度レベル",b:"Level0：手動。Level1：学習パイプライン自動化(CT)。Level2：CI/CD/CTの完全自動化。"},
{d:5,f:"継続的学習(CT)のトリガー",b:"スケジュール、新データ到着、性能劣化/ドリフト検知、コード変更。"},
{d:5,f:"Cloud Build",b:"CI/CD。テスト・コンテナビルド・パイプライン起動をコミット契機で自動化。"},
{d:5,f:"パイプラインのキャッシュ",b:"同一入力・同一コンポーネントの結果を再利用して再実行を省く。"},
{d:5,f:"TFDV",b:"TensorFlow Data Validation。スキーマ異常・スキュー・ドリフトをデータ検証で検知。"},
{d:5,f:"Model Registry",b:"モデルのバージョン・エイリアス・評価を管理し、デプロイの起点になる。"},
{d:6,f:"Skew と Drift の違い",b:"Skew：学習データ vs 本番入力。Drift：本番入力が時間とともに変化（過去の本番がベースライン）。"},
{d:6,f:"コンセプトドリフト",b:"入力と目的変数の関係が変化。正解ラベルでの性能監視が必要。"},
{d:6,f:"Model Monitoring の距離指標",b:"カテゴリ特徴：L∞距離。数値特徴：Jensen-Shannon divergence。しきい値超過でアラート。"},
{d:6,f:"Request-response logging",b:"Endpointの入出力をBigQueryに記録。分析・再学習・監査に使う。"},
{d:6,f:"Cloud Monitoring",b:"レイテンシ・エラー率・使用率などのシステム指標のダッシュボードとアラート。"},
{d:6,f:"生成AIの監視観点",b:"品質(幻覚/関連性)、安全性、レイテンシ、トークン使用量とコスト、トレース。"},
{d:6,f:"ラベル遅延時の監視",b:"入力/予測ドリフトを先行指標にし、ラベルが揃ったら実性能を評価する。"},
{d:6,f:"安全な切り替え",b:"再学習モデルを評価・比較し、traffic split で段階的にロールアウト。ロールバック手段を持つ。"}
];
